export const lightTheme = {
  colors: {
    background: '#f9fafb',
    headerBackground: '#ffffff',
    footerBackground: '#ffffff',
    footerShadow: '#e1e1e1',
    chatBackground: '#ffffff',
    inputBackground: '#f1f3f5',
    buttonBackground: '#4a6edb',
    buttonHoverBackground: '#3b5ecb',
    buttonText: '#ffffff',
    textPrimary: '#222222',
    textSecondary: '#555555',
    linkColor: '#4a6edb',
    scrollbarTrack: '#e1e1e1',
    scrollbarThumb: '#b0b0b0',
    focusOutline: '#4a90e2',
    focusBackground: '#dbe9ff',
    focusText: '#222222',
    reactionBg: '#e1e1e1',
    reactionColor: '#333333',
    reactionActiveBg: '#4a6edb',
    reactionActiveColor: '#ffffff',
    attachmentBg: '#f1f3f5',
    voiceActive: '#ff5252',
    voiceInactive: '#888888',
    toggleBackground: '#cccccc',
    toggleKnob: '#ffffff',
    toggleIcon: '#555555',
    popupBackground: '#ffffff',
    typingIndicator: '#4a6edb',
    noticeInfoBackground: '#d0e7ff',
    noticeWarningBackground: '#fff4d6',
    noticeErrorBackground: '#ffd6d6',
    noticeDismissHover: '#ff0000',
    placeholderBorder: '#cccccc',
    placeholderText: '#999999',
  },
  fonts: {
    primary: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  glass: {
    blur: '10px',
    background: 'rgba(255, 255, 255, 0.7)',
  },
  gradients: {
    primary: 'linear-gradient(135deg, #6b8de3 0%, #4a6edb 100%)',
    secondary: 'linear-gradient(135deg, #f0f0f0 0%, #dcdcdc 100%)',
  },
};

export const darkTheme = {
  colors: {
    background: '#121212',
    headerBackground: '#1f1f1f',
    footerBackground: '#1f1f1f',
    footerShadow: '#000000',
    chatBackground: '#181818',
    inputBackground: '#242424',
    buttonBackground: '#6b8de3',
    buttonHoverBackground: '#577ace',
    buttonText: '#ffffff',
    textPrimary: '#eeeeee',
    textSecondary: '#bbbbbb',
    linkColor: '#6b8de3',
    scrollbarTrack: '#2a2a2a',
    scrollbarThumb: '#555555',
    focusOutline: '#6b8de3',
    focusBackground: '#2a3d66',
    focusText: '#eeeeee',
    reactionBg: '#333333',
    reactionColor: '#dddddd',
    reactionActiveBg: '#6b8de3',
    reactionActiveColor: '#ffffff',
    attachmentBg: '#242424',
    voiceActive: '#ff5252',
    voiceInactive: '#888888',
    toggleBackground: '#555555',
    toggleKnob: '#eeeeee',
    toggleIcon: '#222222',
    popupBackground: '#242424',
    typingIndicator: '#6b8de3',
    noticeInfoBackground: '#2a3d66',
    noticeWarningBackground: '#665c2a',
    noticeErrorBackground: '#662a2a',
    noticeDismissHover: '#ff5252',
    placeholderBorder: '#555555',
    placeholderText: '#777777',
  },
  fonts: {
    primary: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  glass: {
    blur: '15px',
    background: 'rgba(24, 24, 24, 0.7)',
  },
  gradients: {
    primary: 'linear-gradient(135deg, #6b8de3 0%, #4a6edb 100%)',
    secondary: 'linear-gradient(135deg, #2a2a2a 0%, #4a4a4a 100%)',
  },
};
